#!/usr/bin/env node
const { spawn } = require('child_process');

const args = process.argv.slice(2);

let command = "{{command}}";
const argTemplate = '{{arg}}';

args.forEach(arg => {
    if (command.includes(argTemplate)) {
        command = command.replace(argTemplate, arg);
    } else {
        command += (" " + arg);
    }
})

console.log("🚀 quick-cmd ~ full command: ", command);

const child = spawn(command, {
    stdio: 'inherit',
    shell: true
});

child.on('close', (code) => {
    process.exit(code);
});